DEFAULT_NAME_MAX_LENGTH = 255

CATEGORY_IMAGE_UPLOAD_PATH = 'category/'
SUBCATEGORY_IMAGE_UPLOAD_PATH = 'subcategory/'
PRODUCT_ORIGINAL_IMAGE_UPLOAD_PATH = 'products/original/'
PRODUCT_SMALL_IMAGE_UPLOAD_PATH = 'products/small/'
PRODUCT_MEDIUM_IMAGE_UPLOAD_PATH = 'products/medium/'
PRODUCT_LARGE_IMAGE_UPLOAD_PATH = 'products/large/'

PRODUCT_SMALL_IMAGE_SIZE = (150, 150)
PRODUCT_MEDIUM_IMAGE_SIZE = (400, 400)
PRODUCT_LARGE_IMAGE_SIZE = (800, 800)
PRODUCT_IMAGE_SIZES = {
    'image_small': PRODUCT_SMALL_IMAGE_SIZE,
    'image_medium': PRODUCT_MEDIUM_IMAGE_SIZE,
    'image_large': PRODUCT_LARGE_IMAGE_SIZE,
}
PRODUCT_API_IMAGE_FIELDS = ('image_small', 'image_medium', 'image_large')
PRODUCT_JPEG_FORMAT = 'JPEG'
PRODUCT_JPEG_QUALITY = 90

MIN_CART_ITEM_QUANTITY = 1
QUANTITY_POSITIVE_ERROR = 'Количество должно быть больше 0.'
QUANTITY_REQUIRED_ERROR = 'Это поле обязательно.'
